import type { Metadata } from 'next'
import Link from 'next/link'
import Nav from '@/components/Nav'
import Footer from '@/components/Footer'
import { caseStudies } from '@/lib/caseStudies'

export const metadata: Metadata = {
  title: 'Ontario Teacher Unit Planner',
  description:
    'AI lesson planner for Ontario teachers. 3,717 verified curriculum expectations across all 10 Ontario subjects. No hallucinated codes. 14 AI workflows. Director/architect — zero code written.',
  alternates: {
    canonical: 'https://thomascha.com/cs3',
  },
  openGraph: {
    title: 'Ontario Teacher Unit Planner | AI Lesson Planning on Verified Curriculum Data — Thomas Cha',
    description:
      'Every AI planning tool generates fake Ontario curriculum codes. This app loads 3,717 verified Ministry of Education expectations across all 10 Ontario subjects as structured data. AI writes the lessons. The curriculum anchors are guaranteed real. 14 active AI workflows. Zero lines of code written.',
    url: 'https://thomascha.com/cs3',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Ontario Teacher Unit Planner | AI Lesson Planning on Verified Curriculum Data',
    description:
      'AI lesson planner built on 3,717 verified Ontario curriculum expectations across all 10 subjects. No hallucinated codes. 14 active AI workflows. Zero lines of code written by Thomas Cha.',
    images: ['/og-default.jpg'],
  },
}

const articleSchema = {
  '@context': 'https://schema.org',
  '@type': 'Article',
  headline: 'Ontario Teacher Unit Planner — AI Lesson Planning on Verified Curriculum Data',
  description:
    'A full-stack AI-powered lesson planning web application for Ontario teachers, built on 3,717 verified Ministry of Education curriculum expectations across all 10 Ontario subjects. No curriculum content is ever generated by AI.',
  author: {
    '@type': 'Person',
    name: 'Thomas Cha',
    url: 'https://thomascha.com',
    jobTitle: 'AI Implementation Specialist',
  },
  publisher: {
    '@type': 'Person',
    name: 'Thomas Cha',
    url: 'https://thomascha.com',
  },
  datePublished: '2026-07-12',
  dateModified: '2026-07-12',
  url: 'https://thomascha.com/cs3',
  mainEntityOfPage: 'https://thomascha.com/cs3',
  keywords: [
    'Ontario curriculum expectations',
    'AI lesson planning',
    'education technology',
    'verified curriculum data',
    'no-code AI development',
    'AI implementation',
    'Next.js Supabase n8n',
    'director architect',
  ],
  about: [
    { '@type': 'Thing', name: 'Education Technology' },
    { '@type': 'Thing', name: 'AI Lesson Planning' },
    { '@type': 'Thing', name: 'Ontario Ministry of Education Curriculum' },
  ],
}

const breadcrumbSchema = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    {
      '@type': 'ListItem',
      position: 1,
      name: 'Home',
      item: 'https://thomascha.com',
    },
    {
      '@type': 'ListItem',
      position: 2,
      name: 'Ontario Teacher Unit Planner',
      item: 'https://thomascha.com/cs3',
    },
  ],
}

const metaSystem = [
  {
    label: '33-module plan',
    detail:
      'produced upfront by AI before a single module was built. Every module declares its start state, end state, deliverables, interface contracts, and verification steps.',
  },
  {
    label: 'One module per session',
    detail:
      "each AI session targets one module with a clear start and end state. The session can't begin the next module until verification passes on the current one.",
  },
  {
    label: 'Living to-do file',
    detail:
      'read at the start of every session and updated at the end. Any new module, design decision, or change is written back so the next session starts with full context.',
  },
  {
    label: 'Log rotation',
    detail:
      'when a log file grows large enough to become expensive context, the system spawns the next numbered file. The current log plus the to-do file is sufficient to re-orient at the start of any session.',
  },
  {
    label: 'CLAUDE.md',
    detail:
      'carries persistent session instructions that load automatically into every session. Project-level rules that no session can drift from.',
  },
  {
    label: 'Verification steps per module',
    detail: "the session doesn't end until they pass.",
  },
  {
    label: 'Cost and model audits',
    detail:
      'embedded in the workflow as a first-class concern. Four workflows were migrated from the most expensive model to Sonnet after a formal audit found no quality justification for the premium. A further downgrade to a smaller model was tested and reverted.',
  },
]

export default function CS3Page() {
  const cs2 = caseStudies.find((cs) => cs.id === 'cs2')!
  const cs3 = caseStudies.find((cs) => cs.id === 'cs3')!
  const cs4 = caseStudies.find((cs) => cs.id === 'cs-rag')!

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />

      <Nav />

      <main>
        <article aria-labelledby="cs-title" className="max-w-5xl mx-auto px-6 py-12 md:py-16">

          {/* Back link */}
          <Link
            href="/"
            className="inline-block py-3 mb-8 text-sm text-zinc-500 hover:text-blue-600 transition-colors duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 rounded"
          >
            ← thomascha.com
          </Link>

          {/* Header */}
          <header className="mb-12 md:mb-16">
            <p className="text-xs font-medium uppercase tracking-widest text-zinc-400 mb-3">
              Case Study 03
            </p>
            <h1
              id="cs-title"
              className="text-3xl md:text-4xl lg:text-5xl font-bold tracking-tight text-zinc-900 mb-4"
            >
              Ontario Teacher Unit Planner
            </h1>
            <p className="text-lg md:text-xl text-zinc-500 leading-relaxed mb-6">
              A hallucination-resistant AI lesson planning system, designed and directed without a
              line of code written
            </p>
            <div className="flex flex-wrap gap-2">
              {cs3.domains.map((d) => (
                <span
                  key={d}
                  className="text-xs font-medium text-blue-600 bg-blue-50 px-3 py-1 rounded-full"
                >
                  {d}
                </span>
              ))}
            </div>
          </header>

          {/* The Problem */}
          <section aria-labelledby="problem-heading" className="mb-14 md:mb-16">
            <h2
              id="problem-heading"
              className="text-xl md:text-2xl font-semibold text-zinc-800 mb-4"
            >
              The Problem
            </h2>
            <div className="max-w-prose space-y-4">
              <p className="text-base leading-relaxed text-zinc-600">
                Every AI lesson planning tool on the market generates Ontario curriculum expectations
                from general knowledge. That knowledge is wrong at the precision a teacher actually
                needs. Wrong expectation code, the right concept at the wrong grade, a standard from
                another province wearing Ontario&apos;s terminology. A teacher who catches the error
                mid-unit has already built two weeks of lessons on a foundation that doesn&apos;t
                exist.
              </p>
              <p className="text-base leading-relaxed text-zinc-600">
                The second problem is structural. Most AI planning tools generate one lesson at a
                time, with no connection between them. Lesson 1 doesn&apos;t know what Lesson 3
                will cover. There&apos;s no diagnostic layer that adapts the sequence based on what
                students actually know coming in. The output is content delivery wearing the costume
                of a unit plan.
              </p>
              <p className="text-base leading-relaxed text-zinc-600">
                The third problem is that no available tool is built specifically for Ontario. The
                provincial curriculum has its own structure, its own terminology, and its own
                assessment frameworks grounded in the Growing Success policy document. Tools that
                claim provincial support typically provide it as a thin wrapper over generic content.
              </p>
            </div>
          </section>

          {/* The System */}
          <section aria-labelledby="system-heading" className="mb-14 md:mb-16">
            <h2
              id="system-heading"
              className="text-xl md:text-2xl font-semibold text-zinc-800 mb-4"
            >
              The System
            </h2>
            <p className="text-base text-zinc-600 mb-4 max-w-prose">
              A full-stack web application with user accounts, a curriculum database, and a
              two-stage planning workflow. All 3,717 Ontario Ministry of Education curriculum
              expectations across all 10 subjects (Grades 1 through 8, with French programs
              starting at Grade 4) are loaded as verified structured data. No curriculum content
              is ever generated by AI.
            </p>
            <div className="flex flex-wrap gap-2 mb-6">
              {['Next.js', 'Supabase', 'n8n', 'Claude'].map((tech) => (
                <span
                  key={tech}
                  className="text-xs font-medium text-zinc-600 bg-zinc-100 px-3 py-1 rounded-full"
                >
                  {tech}
                </span>
              ))}
            </div>
            <div className="space-y-4 max-w-2xl">
              <div className="border border-zinc-200 rounded-xl p-5 md:p-6">
                <p className="text-xs font-semibold uppercase tracking-widest text-zinc-400 mb-1">
                  Stage 01
                </p>
                <h3 className="text-base font-semibold text-zinc-800 mb-3">
                  Unit Roadmap and Diagnostic
                </h3>
                <p className="text-sm md:text-base leading-relaxed text-zinc-600">
                  The teacher selects curriculum expectations from the verified Ministry database,
                  either by browsing directly or by describing an activity and having the AI map it
                  to matching expectations. The app also surfaces AI-generated cross-curricular
                  suggestions based on the teacher&apos;s selection, recommending expectations from
                  other subjects that fit naturally alongside the primary ones. The app produces a
                  complete unit roadmap: learning goals, a lesson sequence, formative checkpoints,
                  and a diagnostic assessment. The teacher reviews the roadmap, makes adjustments,
                  and administers the diagnostic to their class before anything else is generated.
                </p>
              </div>

              <div className="border border-zinc-200 rounded-xl p-5 md:p-6">
                <p className="text-xs font-semibold uppercase tracking-widest text-zinc-400 mb-1">
                  Stage 02A
                </p>
                <h3 className="text-base font-semibold text-zinc-800 mb-3">
                  Skeleton Review
                </h3>
                <p className="text-sm md:text-base leading-relaxed text-zinc-600">
                  Diagnostic results feed back into the system. The app generates compact lesson
                  skeletons (roughly 400 to 600 tokens each) for every lesson in the unit. The
                  teacher reviews all skeletons before any full generation begins. Lessons can be
                  resequenced, combined, or redirected cheaply at this stage. Only when the teacher
                  approves the outline does full expansion begin.
                </p>
              </div>

              <div className="border border-zinc-200 rounded-xl p-5 md:p-6">
                <p className="text-xs font-semibold uppercase tracking-widest text-zinc-400 mb-1">
                  Stage 02B
                </p>
                <h3 className="text-base font-semibold text-zinc-800 mb-3">
                  On-Demand Expansion
                </h3>
                <p className="text-sm md:text-base leading-relaxed text-zinc-600">
                  Full lesson plans are generated one at a time, when the teacher opens them.
                  Within each lesson, sections are divided into core (generated on expansion) and
                  deferred (generated only when the teacher opens them). If a teacher never opens a
                  deferred section, it&apos;s never generated. If a unit is abandoned mid-way, only
                  the skeleton generation cost was incurred.
                </p>
                <p className="text-sm text-zinc-400 mt-3">
                  Context trimming on this stage reduced input tokens from 14,750 to 4,832 per call
                  (67% reduction) by replacing the full Stage 1 JSON with a filtered object
                  containing only what each lesson expansion actually needs.
                </p>
              </div>
            </div>

            <div className="mt-6 max-w-2xl">
              <p className="text-sm text-zinc-500 leading-relaxed">
                The app also includes a dependency-aware revision cascade (a change to one section
                surfaces affected sections for teacher confirmation), a curriculum coverage tracker
                with four depth levels tied to the Growing Success framework, Bloom&apos;s taxonomy
                and Webb&apos;s DOK built into every generation prompt, teacher style and class
                profile as inputs, export to PDF, DOCX, and Google Docs, an asset generation
                framework (7 asset types, library page, and generation UX built), and an
                owner-only admin analytics dashboard with friction tracking across 30 mapped user
                journey points. Fourteen active AI workflows. Thirteen Supabase tables.
              </p>
            </div>
          </section>

          {/* Recruiter bridge */}
          <div className="max-w-prose mb-14 md:mb-16 bg-zinc-50 border border-zinc-100 rounded-xl px-5 py-4 md:px-6 md:py-5">
            <p className="text-base leading-relaxed text-zinc-700">
              For an AI implementation role, the signal here isn&apos;t the feature list. It&apos;s
              the discipline that kept a 40+ module project coherent, on budget, and on spec across
              46 sessions.
            </p>
          </div>

          {/* Key Architectural Decision */}
          <section aria-labelledby="arch-heading" className="mb-14 md:mb-16">
            <h2
              id="arch-heading"
              className="text-xl md:text-2xl font-semibold text-zinc-800 mb-6"
            >
              Key Architectural Decision
            </h2>

            <div className="max-w-prose space-y-4 mb-8">
              <p className="font-semibold text-zinc-900">The curriculum database</p>
              <p className="text-base leading-relaxed text-zinc-600">
                Curriculum expectations are pulled from a verified structured database before any AI
                call happens. The AI never decides what a curriculum expectation says. It only
                decides how to teach toward expectations the teacher has already selected from
                verified data. No amount of prompt engineering produces what a database does.
              </p>
              <p className="text-base leading-relaxed text-zinc-600">
                Every competitor tool generates curriculum content from an AI model&apos;s general
                knowledge. That knowledge is imprecise at the level Ontario teachers need. Exact
                expectation code, exact wording from the Ministry document, the distinction between
                an overall expectation and a specific one, the correct strand for a given grade.
                The decision here was to solve the problem structurally. Not better prompts.
                A database.
              </p>
            </div>

            <div className="max-w-prose space-y-4">
              <p className="font-semibold text-zinc-900">The development meta-system</p>
              <p className="text-base leading-relaxed text-zinc-600">
                AI sessions are stateless. Each session starts blank. A complex software project
                accumulates far more state than any single session can hold: full product
                specification, all previous decisions, the current module&apos;s interface contracts,
                what the last session verified, what it deferred. Without a deliberate system to
                manage that accumulation, sessions lose coherence. Decisions get re-litigated. Bugs
                come from a session that didn&apos;t know a constraint established three modules
                earlier.
              </p>
              <p className="text-base leading-relaxed text-zinc-600">
                The solution was a development meta-system, designed before a single module was
                built. Seven components:
              </p>
              <div className="bg-zinc-50 border border-zinc-100 rounded-xl p-5 md:p-6">
                <ul className="space-y-3">
                  {metaSystem.map((item) => (
                    <li key={item.label} className="text-sm leading-relaxed text-zinc-600">
                      <span className="font-semibold text-zinc-800">{item.label}. </span>
                      {item.detail}
                    </li>
                  ))}
                </ul>
              </div>
              <p className="text-base leading-relaxed text-zinc-600">
                This protocol ran without context collapse across 40+ modules and 46 sessions. The app is a demonstration of what the methodology can produce. The
                meta-system is a demonstration of how to sustain complex AI-assisted work over time
                without losing the thread.
              </p>
            </div>
          </section>

          {/* The So What */}
          <section aria-labelledby="sowhat-heading" className="mb-14 md:mb-16">
            <h2
              id="sowhat-heading"
              className="text-xl md:text-2xl font-semibold text-zinc-800 mb-4"
            >
              The So What
            </h2>
            <div className="max-w-prose space-y-4">
              <p className="text-base leading-relaxed text-zinc-600">
                The work that breaks most AI-assisted software projects isn&apos;t the AI. It&apos;s
                session management. Context collapse, design drift, decisions re-litigated three
                modules later because no session had access to what an earlier one established. This
                project solved that problem structurally, before a single module was built. The same
                system that produced the app is what any complex AI implementation needs. Bounded
                sessions, interface contracts, a living source of truth, and cost audits embedded
                from the start.
              </p>
              <p className="text-base leading-relaxed text-zinc-600">
                The proof isn&apos;t in the feature list. It&apos;s in the logs. Three log files and
                a to-do document record a consistent, uninterrupted development cycle across 30+
                modules. Brief the AI on the module. Plan. Execute. Verify. Log. Advance. Session
                after session, the same rhythm, applied to a problem complex enough that most people
                would assume it requires a development team.
              </p>
            </div>
          </section>

          {/* Current state callout — before credential line */}
          <div className="max-w-prose mb-14 md:mb-16 border-l-4 border-blue-400 bg-blue-50 rounded-r-xl px-5 py-4 md:px-6 md:py-5">
            <p className="text-xs uppercase tracking-widest text-zinc-400 mb-4">Current State</p>
            <div className="space-y-3">
              <p className="text-base leading-relaxed text-zinc-700">
                Phases 1 through 6 are complete (40+ modules). The app works end-to-end. A real
                teacher can sign up, generate a unit plan, review skeletons, expand lessons, revise
                sections, export documents, and track curriculum coverage.
              </p>
              <p className="text-base leading-relaxed text-zinc-700">
                Phase 7 (IEP modifications, ESL/ELL accommodations, report card comments) has not
                started. Phase 8 asset generation has its infrastructure in place: 7 asset type
                schemas, a library page, and the generation UX are built. Individual asset
                generators (exit tickets, worksheets, quizzes, tests) are next. Deployment to a
                public URL is the next step before Phase 7.
              </p>
            </div>
          </div>

          {/* Closing credential line */}
          <div className="max-w-prose mb-14 md:mb-16">
            <div className="w-8 h-0.5 bg-blue-500 mb-4" aria-hidden="true" />
            <p className="text-xl md:text-2xl font-semibold text-zinc-900 leading-snug">
              Without writing a line of code, he designed and directed the development of a
              full-stack AI-powered web application. Verified curriculum database, multi-phase
              adaptive planning workflow, dependency-aware revision system, coverage tracker, export
              pipeline, and admin analytics dashboard. The same modular session protocol ran
              consistently across 40+ modules and 46 sessions. It maintained zero
              context collapse throughout and produced a working demo a real teacher can use today.
            </p>
          </div>

        </article>

        {/* Prev/Next Navigation */}
        <nav
          aria-label="Case study navigation"
          className="max-w-5xl mx-auto px-6 border-t border-zinc-200 pt-8 mt-4 mb-12 flex flex-wrap items-center justify-between gap-4"
        >
          <Link
            href={cs2.href}
            className="group py-3 flex flex-col focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 rounded"
            aria-label={`Previous case study: ${cs2.title}`}
          >
            <span className="text-xs uppercase tracking-widest text-zinc-400 mb-1">Previous</span>
            <span className="text-sm font-medium text-zinc-700 group-hover:text-blue-600 transition-colors duration-200">
              ← {cs2.number}
            </span>
          </Link>
          <Link
            href={cs4.href}
            className="group py-3 flex flex-col items-end focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 rounded"
            aria-label={`Next case study: ${cs4.title}`}
          >
            <span className="text-xs uppercase tracking-widest text-zinc-400 mb-1">Next</span>
            <span className="text-sm font-medium text-zinc-700 group-hover:text-blue-600 transition-colors duration-200">
              {cs4.number} →
            </span>
          </Link>
        </nav>

      </main>
      <Footer />
    </>
  )
}
