export interface CaseStudy {
  id: 'cs1' | 'cs2' | 'cs3' | 'cs4'
  number: string
  title: string
  domains: string[]
  problem: string
  whatWasBuilt: string
  proofPoint: string
  roleChip: string
  href: string
}

export const caseStudies: CaseStudy[] = [
  {
    id: 'cs1',
    number: 'CS1',
    title: 'AI-Powered SEO Content Production System',
    domains: ['SEO', 'Content', 'Prompt Architecture'],
    problem:
      'Manual SERP analysis for a single keyword took hours to days. Scaling it was unthinkable.',
    whatWasBuilt:
      'A three-stage workflow: AI-directed domain research, encoding the research into a reusable prompt, then deployment against real SERP data. The system autonomously analyzed 8 competing pages, produced a full optimization blueprint, and generated a ~2,500-word article with FAQ content, schema markup, title and meta options, and link suggestions.',
    proofPoint:
      'Same prompt run through Claude and Grok in parallel. Output quality was scored, and each gap drove a specific prompt revision.',
    roleChip: 'Director · Architect · Zero code written',
    href: '/cs1',
  },
  {
    id: 'cs2',
    number: 'CS2',
    title: 'AI-Powered Job Fit Evaluation System',
    domains: ['Workflow Automation', 'Occupational Psychology', 'Prompt Architecture'],
    problem:
      'Evaluating job postings manually was slow, inconsistent, and undocumented. No framework for distinguishing hard mismatches from closable gaps.',
    whatWasBuilt:
      'A three-phase evaluation system grounded in occupational psychology research. Phase 1 produces a role snapshot, fit score, alignment mapping, and divergence analysis (hard mismatches vs. closable gaps). Phase 2 runs an 8-signal environmental red flag screen. Phase 3 produces a structured summary for comparing postings side by side. Prompt refined through multi-model comparison (Fable, Opus, Sonnet) to a 95% benchmark match running at Sonnet cost. 40+ real postings evaluated.',
    proofPoint:
      'Five benchmark refinement rounds: 80% → 85% → ~90% → 93% → 95% Fable-match quality, running at Sonnet cost.',
    roleChip: 'Director · Architect · Zero code written',
    href: '/cs2',
  },
  {
    id: 'cs3',
    number: 'CS3',
    title: 'Ontario Teacher Unit Planner',
    domains: ['Education Tech', 'Full-Stack', 'Workflow Automation'],
    problem:
      'Ontario teachers had two options: hours of manual curriculum cross-referencing, or fast AI tools that hallucinate curriculum expectations. A teacher who catches the error mid-unit has already built on a broken foundation.',
    whatWasBuilt:
      'A full-stack web app (Next.js, Supabase, n8n, Claude) with 14 active AI workflows, 13 Supabase tables, and all 3,717 Ontario Ministry curriculum expectations across all 10 subjects loaded as verified structured data. No curriculum content is ever generated by AI. Two-stage planning workflow: diagnostic-informed lesson skeletons reviewed before full expansion; sections like Teacher Notes and Differentiation are generated on demand. Dependency-aware revision cascade, curriculum coverage tracker, export to PDF/DOCX/Google Docs, asset generation infrastructure, and admin analytics dashboard with friction tracking.',
    proofPoint:
      'Stage 2B context trimming: 14,750 → 4,832 input tokens per call (67% reduction). Four workflows migrated from premium model to Sonnet after cost audit found no quality justification.',
    roleChip: 'Director · Architect · Zero lines of code written',
    href: '/cs3',
  },
  {
    id: 'cs4',
    number: 'CS4',
    title: 'File-Based RAG Architecture',
    domains: ['Knowledge Management', 'RAG', 'Systems Design'],
    problem:
      'Claude has no memory between sessions. Across 8+ active projects spanning months of work, every session was either context-heavy and slow, or context-light and error-prone.',
    whatWasBuilt:
      'A persistent, queryable knowledge base across 8+ AI projects using nothing but structured markdown. Four components: a structured index file per project (entry number, date, timestamp, summary, tags, chunk pointer), chunked log archives capped at ~1,300 lines, per-project tag vocabularies registered in CLAUDE.md, and per-project skill files that specify the exact logging format, keeping every entry consistent across sessions. No database. No vector store. No code.',
    proofPoint:
      'The largest single project: 16 chunk files, 11,800+ lines of archived sessions. Zero database. Zero code.',
    roleChip: 'Director · Architect · Zero code written',
    href: '/cs4',
  },
]
